# Generated by Django 4.2 on 2023-06-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetomany', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gens',
            old_name='genre',
            new_name='sofia',
        ),
    ]
